### ISSUE TITLE
Import error of pyknp

### ISSUE THREAD

**Issue by Kensuke-Mitsuzawa** [Kensuke-Mitsuzawa/JapaneseTokenizers#43]
```
Traceback (most recent call last):
  File "generate_theme1.py", line 3, in <module>
    from JapaneseTokenizer import MecabWrapper
  File "/share/data/home/kensuke_mitsuzawa/outsource-ds-py-company-review/conda-env/lib/python3.5/site-packages/JapaneseTokenizer/__init__.py", line 2, in <module>
    from JapaneseTokenizer.juman_wrapper import JumanWrapper
  File "/share/data/home/kensuke_mitsuzawa/outsource-ds-py-company-review/conda-env/lib/python3.5/site-packages/JapaneseTokenizer/juman_wrapper/__init__.py", line 2, in <module>
    from .juman_wrapper import JumanWrapper
  File "/share/data/home/kensuke_mitsuzawa/outsource-ds-py-company-review/conda-env/lib/python3.5/site-packages/JapaneseTokenizer/juman_wrapper/juman_wrapper.py", line 11, in <module>
    from pyknp import MList
ImportError: No module named 'pyknp'
```

**Comment by mohammad-** [comment]
I was able to keep going with following commands on python 3.5 docker container.

```
wget -O pyknp-0.3.tar.gz  http://lotus.kuee.kyoto-u.ac.jp/nl-resource/pyknp/pyknp-0.3.tar.gz
tar xf pyknp-0.3.tar.gz 
cd pyknp-0.3
61  python setup.py install 
```

**Comment by Kensuke-Mitsuzawa** [comment]
This issue is solved already. Close
