### ISSUE TITLE
Can not install with dependency problem

### ISSUE THREAD

**Issue by Kensuke-Mitsuzawa** [Kensuke-Mitsuzawa/JapaneseTokenizers#6]
```
MacBook-Pro% pip install JapaneseTokenizer
Requirement already satisfied (use --upgrade to upgrade): JapaneseTokenizer in /Users/kensuke-mi/Desktop/analysis_work/python_morphology_splitters
Requirement already satisfied (use --upgrade to upgrade): future in /Users/kensuke-mi/.pyenv/versions/3.5.1/lib/python3.5/site-packages/future-0.15.2-py3.5.egg (from JapaneseTokenizer)
Requirement already satisfied (use --upgrade to upgrade): six in /Users/kensuke-mi/.pyenv/versions/3.5.1/lib/python3.5/site-packages (from JapaneseTokenizer)
Collecting mecab-python (from JapaneseTokenizer)
  Downloading mecab-python-0.996.tar.gz (40kB)
    100% |████████████████████████████████| 40kB 6.4MB/s 
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/private/var/folders/nq/13lcpk354h51bgkmx4q4ttr00000gp/T/pip-build-kd5ixe8l/mecab-python/setup.py", line 18, in <module>
        include_dirs=cmd2("mecab-config --inc-dir"),
      File "/private/var/folders/nq/13lcpk354h51bgkmx4q4ttr00000gp/T/pip-build-kd5ixe8l/mecab-python/setup.py", line 10, in cmd2
        return string.split (cmd1(str))
    AttributeError: module 'string' has no attribute 'split'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/nq/13lcpk354h51bgkmx4q4ttr00000gp/T/pip-build-kd5ixe8l/mecab-python
You are using pip version 7.1.2, however version 8.1.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
```

**Comment by Peibolvig** [comment]
There are two versions of mecab-python in PyPi:
* mecab-python (for Python 2.x)
* mecab-python3 (for Python3.x)

That error is probably because you are trying to install mecab-python using the python3 pip.

**Comment by Kensuke-Mitsuzawa** [comment]
@Peibolvig Thanks for your suggestion. I found that this issue is old one. I guess it has been out of my mind to close this issue.
At least, in the latest version `1.2.7` , this issue does not happen in following python versions

- 2.7.11
- 3.5.0
- 3.5.2
